version: '3'
services:

  postgresdb:
    image: postgres:14-alpine
    restart: unless-stopped
    env_file:
    - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}'
    volumes:
      - postgresdata:/var/lib/postgresql/data/pgdata

  keycloak:
    depends_on:
      - keycloak-db
    image: jboss/keycloak
    restart: always
    environment:
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - '${KEYCLOAK_LOCAL_PORT}:${KEYCLOAK_DOCKER_PORT}'
    networks:
      - local-keycloak

  keycloak-db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - local-keycloak

  web:
    depends_on:
      - postgresdb
    build: .
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:postgresql://postgresdb:$POSTGRES_DOCKER_PORT/$POSTGRES_DB?useSSL=false",
        "spring.datasource.username" : "$POSTGRES_USER",
        "spring.datasource.password" : "$POSTGRES_PASSWORD",
        "spring.datasource.driver-class-name" : "org.postgresql.Driver",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "$HIBERNATE_DDL_AUTO"
      }'
    ports:
      - '${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}'

volumes:
  postgresdata: {}

networks:
  local-keycloak: