version: '3'
services:
  postgresdb:
    image: postgres:14-alpine
    restart: always
    env_file:
    - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '$POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT'
    volumes:
      - postgresdata:/var/lib/postgresql/data/pgdata

  web:
    depends_on:
      - postgresdb
    build: .
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:postgresql://postgresdb:$POSTGRES_DOCKER_PORT/$POSTGRES_DATABASE?useSSL=false",
        "spring.datasource.username" : "$POSTGRES_USER",
        "spring.datasource.password" : "$POSTGRES_PASSWORD",
        "spring.datasource.driver-class-name" : "org.postgresql.Driver",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "$HIBERNATE_DDL_AUTO"
      }'
    ports:
      - '$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT'

volumes:
  postgresdata: {}